"""TEST

Revision ID: 00ea37ad53cc
Revises: e544bd5c70e8
Create Date: 2023-11-10 13:09:35.881134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00ea37ad53cc'
down_revision: Union[str, None] = 'e544bd5c70e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_referral_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'referral_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('referral_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_referral_id_fkey', 'user', 'referral', ['referral_id'], ['id'])
    # ### end Alembic commands ###
