"""Update

Revision ID: 2a5a9d2f6e8d
Revises: 1fb0567952f3
Create Date: 2023-11-19 00:55:29.433597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a5a9d2f6e8d'
down_revision: Union[str, None] = '1fb0567952f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('referral_referring_user_id_fkey', 'referral', type_='foreignkey')
    op.drop_constraint('referral_referred_user_id_fkey', 'referral', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('referral_referred_user_id_fkey', 'referral', 'user', ['referred_user_id'], ['id'])
    op.create_foreign_key('referral_referring_user_id_fkey', 'referral', 'user', ['referring_user_id'], ['id'])
    # ### end Alembic commands ###
