"""Referral added

Revision ID: e544bd5c70e8
Revises: 
Create Date: 2023-11-09 20:32:08.096243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e544bd5c70e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referral_code', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_code')
    )
    op.add_column('user', sa.Column('referral_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'referral', ['referral_id'], ['id'])
    op.drop_column('user', 'referral_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('referral_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'referral_id')
    op.drop_table('referral')
    # ### end Alembic commands ###
